services:
  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    image: subwate/spring-app:latest
    ports:
      - "8080:8080"
    environment:
      SWAGGER_ENABLED: "false"
      SPRING_DATASOURCE_URL: "${DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"

  spring-app-develop:
    build:
      context: .
      dockerfile: dockerfile
    image: subwate/spring-app-develop:latest
    ports:
      - "8081:8080"
    env_file: .env
    environment:
      SWAGGER_ENABLED: "true"
      SPRING_DATASOURCE_URL: "${DB_URL_DEVELOP}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
