services:
  subwate-server:
    build:
      context: .
      dockerfile: dockerfile
    image: subwatedev/subwate-server:latest
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_ENABLED=false

  subwate-server-dev:
    build:
      context: .
      dockerfile: dockerfile
    image: subwatedev/subwate-server-dev:latest
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_ENABLED=true