spring:
  profiles:
    active: db
  config:
    import: "classpath:keys.properties" 
  application:
    name: subwate-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

api:
  seoul_data_api_key: ${seoul_data_api_key}