spring:
  application:
    name: subwate-backend
  doc:
    swagger-ui:
      path: /swagger-ui.html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_OPTION:none}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.MySQLDialect


jwt:
  secret_key: ${jwt_key}

kakao:
  client_id: ${kakao_client_id}
  redirect_uri: http://localhost:8080/api/v1/auth/kakao/callback

