name: ci-cd.main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Execute Permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t subwate/spring-app:latest .

      - name: Push Docker Image
        run: |
          docker push subwate/spring-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DB_URL_DEVELOP: ${{ secrets.DB_URL_DEVELOP }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          scp -i /tmp/ssh_key -o StrictHostKeyChecking=no docker-compose.yml ubuntu@43.200.133.172:/home/ubuntu/

          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no ubuntu@43.200.133.172 << EOF
            cd /home/ubuntu/

            export COMPOSE_HTTP_TIMEOUT=300
            echo "DB_URL=${DB_URL}" > .env
            echo "DB_USERNAME=${DB_USERNAME}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env

            docker-compose stop spring-app
            docker container prune -f
            docker image prune -a -f
            docker volume prune -f
            docker system prune -a -f
            
            docker-compose pull spring-app
            docker-compose up -d spring-app
          EOF